name: virteng-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7.9
  - fortran-compiler=1.0.4
  - matplotlib=3.3.3
  - jupyter=1.0.0
  - jupytext=1.7.1
  - scipy=1.5.3
  - pyyaml=5.3.1
  - numpy=1.19.4
  - xlrd=1.2.0
  - joblib=1.0.0
  - scikit-learn=0.22.1
  - pandas=1.2.3
  - pip
  - pip:
    - -e .
prefix: /opt/anaconda3/envs/virteng-env
